version: '3.5'
services:

    api:
        build: 
            context: .
            target: api-dev
        container_name: movie-app-api
        ports:
            - 8080:8080
        volumes:
            - .:/workspace:cached
            - ./api:/app
            - /app/modules
        environment:
            - PORT=8080
            - APPNAME=${APPNAME}
            - ENVIRONMENT=${ENVIRONMENT}
            - DB_CONNECTIONSTRING=${DB_CONNECTIONSTRING}
            - DB_CLASS=${DB_CLASS}
            - DB_BUNDLENAME=${DB_BUNDLENAME}
            - DB_BUNDLEVERSION=${DB_BUNDLEVERSION}
            - DB_USER_FILE=/run/secrets/DB_USER
            - DB_PASSWORD_FILE=/run/secrets/DB_PASSWORD
            - OMDB_API_KEY=${OMDB_API_KEY}
        secrets:
            - DB_PASSWORD
            - DB_USER
    
    db:
        image: mysql:latest
        container_name: movie-app-db
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/DB_ROOT_PASSWORD
            - MYSQL_USER_FILE=/run/secrets/DB_USER
            - MYSQL_PASSWORD_FILE=/run/secrets/DB_PASSWORD
            - MYSQL_DATABASE=my_movies_db
        secrets:
            - DB_PASSWORD
            - DB_USER
            - DB_ROOT_PASSWORD

    app:
        build:
            context: .
            target: app-dev
        volumes:
        - .:/workspace:cached
        - ./app:/workspace/app
        - /workspace/app/node_modules
        container_name: movie-app
        ports:
            - 3000:3000
        links:
            - api
        environment: 
            CHOKIDAR_USEPOLLING: 'true'

secrets:
  DB_USER:
    file: ./secrets/MYSQL_USER
  DB_PASSWORD:
    file: ./secrets/MYSQL_PASSWORD
  DB_ROOT_PASSWORD:
    file: ./secrets/MYSQL_ROOT_PASSWORD