version: '3.5'
services:
    
    app:
        build: 
            context: .
            target: app-devcontainer
        volumes:
            - .:/workspace:cached
            - ./app:/workspace/app
            - /workspace/app/node_modules
        command: /bin/sh -c "while sleep 1000; do :; done"