
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    test:
      runs-on: ubuntu-latest
      env:
          APPNAME: "movie-list-app"
          ENVIRONMENT: "development"
          DB_CONNECTIONSTRING: "jdbc:mysql://movie-app-db:3306/my_movies_db?useUnicode=true&characterEncoding=UTF8&serverTimezone=America/Chicago&maxReconnects=3&useLegacyDatetimeCode=true"
          DB_CLASS: "com.mysql.cj.jdbc.Driver"
          DB_DRIVER: "MySQL"
          DB_BUNDLENAME: "com.mysql.cj"
          DB_BUNDLEVERSION: "8.0.19"
          OMDB_API_KEY: ""
      steps:  
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup DB credentials
        run: 
          mkdir secrets
          openssl rand 20 | base64 -w 0 > ./secrets/MYSQL_ROOT_PASSWORD 
          openssl rand 20 | base64 -w 0 > ./secrets/MYSQL_PASSWORD 
          echo "mydbuser" > ./secrets/MYSQL_USER
   
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Execute API tests
        run: docker exec -it movie-app-api box testbox run
